openapi: 3.0.3
info:
  title: Budgeting API
  version: 1.0.0
servers:
  - url: /
paths:
  /api/v1/budgets/organizational-unit/{organizationalUnitId}:
    $ref: './budgeting/paths/budgets_by_ou.v1.yaml'
  /api/v1/budgets/organizational-unit:
    $ref: './budgeting/paths/budgets_create_ou.v1.yaml'
