openapi: 3.0.3
info:
  title: Budgeting API
  version: 1.0.0
servers:
  - url: /
paths:
  /api/v1/budgets:
    $ref: './budgeting/paths/budgets.v1.yaml'
  /api/v1/budgets/{id}:
    $ref: './budgeting/paths/budgets_by_id.v1.yaml'
