openapi: 3.0.3
info:
  title: Training API
  version: 1.0.0
servers:
  - url: /
paths:
  /api/v1/trainings:
    $ref: './training/paths/trainings.v1.yaml'
  /api/v1/trainings/{id}:
    $ref: './training/paths/trainings_by_id.v1.yaml'
