type: object
required:
  - id
  - name
  - costAmount
  - costCurrency
  - requestedByName
  - purposeType
  - typeId
  - hours
  - attendees
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
  costAmount:
    type: number
  costCurrency:
    type: string
  requestedByName:
    type: string
  purposeType:
    type: string
  purposeDescription:
    type: string
  typeId:
    type: integer
    format: int64
  hours:
    type: integer
    format: int32
  attendees:
    type: array
    items:
      $ref: './TrainingAttendeeDetails.yaml'
