CREATE SEQUENCE employee_seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE organizational_unit_seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE budget_seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE training_seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE external_provider_seq START WITH 100 INCREMENT BY 1 NOCACHE;
