ALTER TABLE employee ADD active NUMBER(1, 0) DEFAULT 1 NOT NULL;
ALTER TABLE organizational_unit ADD active NUMBER(1, 0) DEFAULT 1 NOT NULL;
ALTER TABLE budget ADD active NUMBER(1, 0) DEFAULT 1 NOT NULL;
ALTER TABLE training ADD active NUMBER(1, 0) DEFAULT 1 NOT NULL;
